# -*- coding: utf-8 -*-
"""
Created on Tue Nov 13 00:00:46 2018

@author: Manish
"""

from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
import cmath
import math
import scipy.io.wavfile
from scipy.fftpack import dct,idct
from scipy.fftpack import fft,ifft

def meanSquaredError(s1,s2):
    arr = abs((s1-s2))
    sum = 0.0
    for i in range(len(arr)):
        sum = sum + (arr[i]*arr[i])
    sum = sum/np.float(len(arr))
    return sum

# Read the same audio file which was used by Compressor.py 
# Use this data for computing MSE before and after compression
[rate,data] = scipy.io.wavfile.read("audio3.wav", mmap=False)

# start time in seconds. t_start = 0 sec, since it is a 1 sec audio file
t_start = 0
t_end = (t_start + 1)

N_ = 44100
start_index = t_start * N_
end_index = t_end * N_
signal = data[start_index:end_index]
l_channel = signal[:,0]
r_channel = signal[:,1]

# This is the left and right channel of original music file
x_l = l_channel
x_r = r_channel

# Read the compressed file generated by Compressor.py
X = np.loadtxt('compressedFile.txt')
N = np.int(X[0,0])
M = np.int(X[0,1])
print('N = '+str(N)+'     M = '+str(M))

XDCT_L_m = np.pad(X[1:,0], (0, M), 'constant')
XDCT_R_m = np.pad(X[1:,1], (0, M), 'constant')
xdct_l_m = scipy.fftpack.idct(XDCT_L_m,norm = 'ortho')
xdct_r_m = scipy.fftpack.idct(XDCT_R_m,norm = 'ortho')
signal_decompressed = np.vstack((xdct_l_m, xdct_r_m)).T

mse_l = meanSquaredError(x_l,xdct_l_m)
mse_r = meanSquaredError(x_r,xdct_r_m)
print('MSE Left Channel = '+str(mse_l))
print('MSE Right Channel = '+str(mse_r))
idx_l = np.argmax(abs(x_l-xdct_l_m))
m_l = max(abs(x_l-xdct_l_m))
idx_r = np.argmax(abs(x_r-xdct_r_m))
m_r = max(abs(x_r-xdct_r_m))
print('Max Error Left Channel = '+str(m_l))
print('Max Error Right Channel = '+str(m_r))
